# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a2a33b73b909e29282d2964ebe1d2fc1c2b53de61d90bbbb91a54346e4b9e06bf9b481024f16b856e6ee35dff02aac2ea7c2ee28e8ea1cf65f72bab7755b6f

test:
  secret_key_base: c45b3af5d81e0ec65c6982c514976d3df99ba7e12c4d8577290e0eb4c1d08067e17de2e759fcdb52de29af22f6a06cf351cb4873a7cd3808d6ac765c5d146526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
